version: '3.5'

services: 
    frontend:
        image: frontend-example
        build: frontend

    backend:
        image: backend-example
        build: backend
        environment: 
            - REDIS=redis-cache
            - DB_HOST=db
            - DB_USERNAME=postgres
            - DB_PASSWORD=qgXzmqYF
        volumes: 
            - ./logs.txt:/backend/logs.txt
    
    redis-cache:
        image: redis:alpine
        restart: unless-stopped
        volumes:
            - cache:/data
        command: redis-server --appendonly yes

    db:
        image: postgres:alpine
        restart: unless-stopped
        environment: 
            - POSTGRES_PASSWORD=qgXzmqYF
        volumes:
            - database:/var/lib/postgresql/data

    proxy:
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
    database:
    cache:

        