FROM openjdk:8-jdk as build-stage
WORKDIR /spring-example
RUN git clone --depth 1 https://github.com/docker-hy/spring-example-project.git .
RUN ./mvnw package

FROM openjdk:8-jre-slim
WORKDIR /spring-example
EXPOSE 8080
RUN useradd -m app && chown app /spring-example
USER app
COPY --from=build-stage /spring-example/target/docker-example-1.1.3.jar /spring-example
CMD [ "java", "-jar", "/spring-example/docker-example-1.1.3.jar" ]