version: '3.5'

services: 
    frontend:
        image: frontend-example
        build: ../../Part1/10
        environment: 
            - API_URL=http://localhost

    backend:
        image: backend-example
        build: ../../Part1/11
        environment: 
            - FRONT_URL=http://localhost
            - REDIS=redis-cache
            - DB_HOST=db
            - DB_USERNAME=postgres
            - DB_PASSWORD=qgXzmqYF
        volumes: 
            - ./logs.txt:/backend/logs.txt
    
    redis-cache:
        image: redis:alpine

    db:
        image: postgres:alpine
        restart: unless-stopped
        environment: 
            - POSTGRES_PASSWORD=qgXzmqYF

    proxy:
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
