version: '3.5'

services: 
    frontend:
        image: kurkkumopo-frontend
        build: ml-kurkkumopo-frontend
        ports:
            - "3000:3000"
        depends_on: 
            - backend

    backend:
        image: kurkkumopo-backend
        build: ml-kurkkumopo-backend
        ports:
            - "5000:5000"
        volumes:
            - model:/src/model

    training:
        image: kurkkumopo-training
        build: ml-kurkkumopo-training
        volumes:
            - model:/src/model
            - images:/src/imgs

volumes:
    model:
    images: